stages:
  root-do-unrelated-stuff:
    cmd: python tests/dvc_pipelines/root/data.py do-unrelated-stuff
    deps:
      - tests/dvc_pipelines/root/data.py
    outs:
      - tests/dvc_pipelines/root/files/unrelated.json:
          cache: false
    frozen: true

  root-import-data-blue:
    cmd: python tests/dvc_pipelines/root/data.py import-data-blue
    deps:
      - tests/dvc_pipelines/root/files/raw_blue.json
      - tests/dvc_pipelines/root/data.py
    outs:
      - tests/dvc_pipelines/root/files/blue.json:
          cache: false
    frozen: true

  root-import-data-red:
    cmd: python tests/dvc_pipelines/root/data.py import-data-red
    deps:
      - tests/dvc_pipelines/root/files/raw_red.json
      - tests/dvc_pipelines/root/data.py
    outs:
      - tests/dvc_pipelines/root/files/red.json:
          cache: false
    frozen: true

  root-create-dataset:
    cmd: python tests/dvc_pipelines/root/features.py create-dataset
    deps:
      - tests/dvc_pipelines/root/features.py
      - tests/dvc_pipelines/root/files/blue.json
      - tests/dvc_pipelines/root/files/red.json
    outs:
      - tests/dvc_pipelines/root/files/dataset.json:
          cache: false
    frozen: true

  root-find-hyperparameters:
    cmd: python tests/dvc_pipelines/root/model.py find-hyperparameters
    deps:
      - tests/dvc_pipelines/root/model.py
    outs:
      - tests/dvc_pipelines/root/files/hyperparameters.json:
          cache: false
    frozen: true

  root-train-model:
    cmd: python tests/dvc_pipelines/root/model.py train-model
    deps:
      - tests/dvc_pipelines/root/model.py
      - tests/dvc_pipelines/root/files/dataset.json
      - tests/dvc_pipelines/root/files/hyperparameters.json
      - tests/dvc_pipelines/root/files/blue.json
    outs:
      - tests/dvc_pipelines/root/files/model.json:
          cache: false
    frozen: true

  root-train-models:
    foreach:
      - out_of_sample
      - out_of_time
      - full
    do:
      cmd: python tests/dvc_pipelines/root/model.py train-model --kind ${item}
      deps:
        - tests/dvc_pipelines/root/model.py
        - tests/dvc_pipelines/root/files/dataset.json
        - tests/dvc_pipelines/root/files/hyperparameters.json
        - tests/dvc_pipelines/root/files/blue.json
      outs:
        - tests/dvc_pipelines/root/files/model-${item}.json:
            cache: false
      frozen: true

  root-generate-dag:
    cmd: dvc-dag
      --delete-text "dvc_pipelines/"
      --delete-text "tests/"
      --merge-stage "root-train-models|kind"
      --merge-stage "dvc_pipelines/model/dvc.yaml|nested-train-models=kind"
      --colors-random-seed 12
      --out docs/dvc_dag.png
    deps:
      - dvc_dag/draw.py
      - dvc_dag/cli.py
    outs:
      - docs/dvc_dag.png:
          cache: false
